document.querySelectorAll(".photo-card").forEach((card) => { card.addEventListener("click", (event) => { for (let i = 0; i < 8; i++) { const heart = document.createElement("span"); heart.className = "floating-heart"; heart.textContent = i % 2 ? "✨" : "♥"; heart.style.left = `${event.clientX + (Math.random() - .5) * 60}px`; heart.style.top = `${event.clientY + (Math.random() - .5) * 30}px`; heart.style.setProperty("--x", `${(Math.random() - .5) * 120}px`); document.body.appendChild(heart); setTimeout(() => heart.remove(), 950); } }); });
const song = document.querySelector("#ourSong"), musicToggle = document.querySelector("#musicToggle"), musicStatus = document.querySelector("#musicStatus"), progress = document.querySelector("#songProgress"), currentTime = document.querySelector("#currentTime"), duration = document.querySelector("#duration");
const formatTime = (time) => `${Math.floor(time / 60)}:${String(Math.floor(time % 60)).padStart(2, "0")}`;
musicToggle.addEventListener("click", async () => { try { if (song.paused) { await song.play(); musicToggle.textContent = "❚❚"; musicStatus.textContent = "Now playing our song ♥"; } else { song.pause(); musicToggle.textContent = "▶"; musicStatus.textContent = "Tap play and remember us ♥"; } } catch { musicStatus.textContent = "Song could not play — please refresh once."; } });
song.addEventListener("loadedmetadata", () => { duration.textContent = formatTime(song.duration); });
song.addEventListener("timeupdate", () => { currentTime.textContent = formatTime(song.currentTime); progress.value = song.duration ? (song.currentTime / song.duration) * 100 : 0; });
progress.addEventListener("input", () => { if (song.duration) song.currentTime = (progress.value / 100) * song.duration; });
document.querySelector("#restartSong").addEventListener("click", () => { song.currentTime = 0; });
document.querySelector("#muteToggle").addEventListener("click", (event) => { song.muted = !song.muted; event.currentTarget.textContent = song.muted ? "🔇" : "♬"; });
